config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :activists

  namespace :admins do
    resources :hot_issues
  end

end

app/models/activist.rb
class Activist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :team_memberships, dependent: :destroy
  has_many :teams, through: :team_memberships
  has_many :hot_issues, through: :teams
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable
end

app/models/hot_issue.rb
class HotIssue < ActiveRecord::Base

  has_many :teams
  has_many :team_memberships, through: :teams
  has_many :activists, through: :team_memberships

  validates :title, presence: true

  def join(activist)
    t = teams.any? ? teams.first : Team.create(hot_issue_id: id)
    t.join(activist)
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  MAX_MEMBER_COUNT = 6

  belongs_to :hot_issue
  has_many :team_memberships, dependent: :destroy
  has_many :activists, through: :team_memberships

  scope :needing_members, -> (hot_issue_id) {
    joins(:team_memberships).
      where("teams.hot_issue_id = ?", hot_issue_id).
      having("COUNT(team_memberships.id) < 6").
      group("teams.id")
  }

  def join(activist)
    team_to_add_new_member_to.
      team_memberships.create(activist: activist)
  end

  def full?
    MAX_MEMBER_COUNT <= team_memberships.count
  end

private

  def team_to_add_new_member_to
    full? ? next_team_to_add_to : self
  end

  def next_team_to_add_to
    t = Team.needing_members(hot_issue_id).first
    t.present? ? t : Team.create(hot_issue: hot_issue)
  end
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  belongs_to :team
  belongs_to :activist
end

app/controllers/admins/applications_controller.rb
class Admins::ApplicationController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admins/hot_issues_controller.rb
class Admins::HotIssuesController < Admins::ApplicationController

  def index
    @hot_issues = HotIssue.all
  end

  def edit
    hot_issue
  end

  def update
    if hot_issue.update_attributes(hot_issue_params)
      redirect_to admins_hot_issues_path
    else
      render 'edit'
    end
  end

private

  def hot_issue
    @hot_issue = HotIssue.find(params[:id])
  end

  def hot_issue_params
    params.require(:hot_issue).permit(:category, :title, :source_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admins/hot_issues_helper.rb
module Admins::HotIssuesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/hot_issues/_form.html.erb
<%= form_for [:admins, @hot_issue] do |f| %>
  <%= f.text_field :category %>
  <%= f.text_field :title %>
  <%= f.text_field :source_url %>
  <%= f.submit %>
<% end %>

app/views/admins/hot_issues/_hot_issue_row.html.erb
  <tr>
    <td><%= hot_issue_row.category %></td>
    <td><%= hot_issue_row.title %></td>
    <td><%= link_to "View source", hot_issue_row.source_url %>
    | <%= link_to "Edit", edit_admins_hot_issue_path(hot_issue_row) %></td>
  </tr>

app/views/admins/hot_issues/edit.html.erb
<%= render 'form' %>

app/views/admins/hot_issues/index.html.erb
<table>
  <tr>
    <th>Category</th>
    <th>Title</th>
    <th>Source url</th>
  </tr>

  <%= render partial: 'hot_issue_row',
             collection: @hot_issues %>

</table>

app/views/admins/hot_issues/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialJusticeWarrior</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>